# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc60f84206f655aaa37c438de9a471a7041b9c3abb71078df7675fc3eccade64b179b6da66ce82657151fa2078a7eea9b64f20625f3a11c58ddcd1e1d16d6084

test:
  secret_key_base: 7fb6ae673890a9ef57d27a6f77343b337b4ef261c45a4e0969d74ee6f0d544223454e57f564d346e8c059a9f691d4b894383a9eb93f19eb5f1aecd8ac9301856

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
